#!/usr/bin/env python3
"""
Turn-focused MRAC diagnostic tool.

Input:
  A parsed_samples.csv generated by scripts/plot_mrac_validation.py

If no input is given, the newest:
  logs/mrac_tests/plots/*/parsed_samples.csv

is used.

Outputs:
  - turn_diagnostics_summary.csv
  - top_events.csv
  - zoom plots around the largest steering/yaw events
"""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path
from typing import List, Optional, Tuple

import matplotlib.pyplot as plt


KEYS_TO_PLOT = [
    "inner_uc",
    "r_recon",
    "inner_e_r",
    "inner_delta_baseline_deg",
    "inner_delta_final_deg",
    "inner_delta_raw_deg",
    "outer_pwm_baseline",
    "outer_pwm_final",
    "phase7_pwm_common",
    "phase7_pwm_diff",
    "vx_recon",
    "speed_cmd",
]


def latest_parsed_csv() -> Path:
    candidates = sorted(
        Path("logs/mrac_tests/plots").glob("*/parsed_samples.csv"),
        key=lambda p: p.stat().st_mtime,
    )
    if not candidates:
        raise SystemExit("No parsed_samples.csv found under logs/mrac_tests/plots/*/")
    return candidates[-1]


def to_float(value) -> Optional[float]:
    if value is None:
        return None

    text = str(value).strip()
    if text in ("", "None", "nan", "NaN"):
        return None
    if text == "True":
        return 1.0
    if text == "False":
        return 0.0
    if text.endswith("deg"):
        text = text[:-3]

    try:
        out = float(text)
    except ValueError:
        return None

    if not math.isfinite(out):
        return None
    return out


def read_csv(path: Path) -> List[dict]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def value(row: dict, key: str, default: float = 0.0) -> float:
    out = to_float(row.get(key))
    if out is None:
        return default
    return out


def sign(x: float) -> int:
    if x > 0.0:
        return 1
    if x < 0.0:
        return -1
    return 0


def window_rows(rows: List[dict], t_center: float, half_window_s: float) -> List[dict]:
    out = []
    for row in rows:
        t = value(row, "_t")
        if t_center - half_window_s <= t <= t_center + half_window_s:
            out.append(row)
    return out


def write_summary(rows: List[dict], out_dir: Path) -> Path:
    metrics = []

    def add(name: str, val):
        metrics.append((name, val))

    add("sample_count", len(rows))
    if rows:
        add("duration_s", value(rows[-1], "_t") - value(rows[0], "_t"))

    for key in [
        "inner_uc",
        "r_recon",
        "inner_e_r",
        "inner_delta_baseline_deg",
        "inner_delta_final_deg",
        "inner_delta_raw_deg",
        "outer_pwm_baseline",
        "outer_pwm_final",
        "phase7_pwm_diff",
        "vx_recon",
    ]:
        vals = [value(r, key) for r in rows if to_float(r.get(key)) is not None]
        if not vals:
            continue
        add(f"{key}_min", min(vals))
        add(f"{key}_max", max(vals))
        add(f"{key}_mean", sum(vals) / len(vals))
        add(f"{key}_max_abs", max(abs(v) for v in vals))

    diffs = []
    sign_mismatch_count = 0
    checked_sign_count = 0

    for row in rows:
        baseline = value(row, "inner_delta_baseline_deg")
        final = value(row, "inner_delta_final_deg")
        diffs.append(final - baseline)

        if abs(baseline) > 2.0 and abs(final) > 2.0:
            checked_sign_count += 1
            if sign(baseline) != sign(final):
                sign_mismatch_count += 1

    if diffs:
        add("inner_delta_final_minus_baseline_mean_deg", sum(diffs) / len(diffs))
        add("inner_delta_final_minus_baseline_max_abs_deg", max(abs(v) for v in diffs))

    if checked_sign_count:
        add("steering_sign_mismatch_count_abs_gt_2deg", sign_mismatch_count)
        add(
            "steering_sign_mismatch_percent_abs_gt_2deg",
            100.0 * sign_mismatch_count / checked_sign_count,
        )

    out_path = out_dir / "turn_diagnostics_summary.csv"
    with out_path.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["metric", "value"])
        writer.writerows(metrics)

    return out_path


def find_top_events(rows: List[dict], top_n: int) -> List[Tuple[float, str, float, int]]:
    events = []

    for i, row in enumerate(rows):
        t = value(row, "_t")

        baseline = value(row, "inner_delta_baseline_deg")
        final = value(row, "inner_delta_final_deg")
        raw = value(row, "inner_delta_raw_deg")
        uc = value(row, "inner_uc")
        r = value(row, "r_recon")
        er = value(row, "inner_e_r")
        pwm_base = value(row, "outer_pwm_baseline")
        pwm_final = value(row, "outer_pwm_final")

        events.append((t, "largest_abs_final_steering_deg", abs(final), i))
        events.append((t, "largest_final_minus_baseline_deg", abs(final - baseline), i))
        events.append((t, "largest_raw_steering_deg", abs(raw), i))
        events.append((t, "largest_yaw_rate_error", abs(er), i))
        events.append((t, "largest_r_minus_uc", abs(r - uc), i))
        events.append((t, "largest_outer_pwm_correction", abs(pwm_final - pwm_base), i))

    events.sort(key=lambda x: x[2], reverse=True)

    selected = []
    used_times = []

    for event in events:
        t = event[0]
        if any(abs(t - old_t) < 2.0 for old_t in used_times):
            continue
        selected.append(event)
        used_times.append(t)
        if len(selected) >= top_n:
            break

    return selected


def write_events(rows: List[dict], events: List[Tuple[float, str, float, int]], out_dir: Path) -> Path:
    out_path = out_dir / "top_events.csv"

    fields = [
        "event_rank",
        "event_type",
        "event_score",
        "_t",
        "vx_recon",
        "speed_cmd",
        "inner_uc",
        "r_recon",
        "inner_e_r",
        "inner_delta_baseline_deg",
        "inner_delta_raw_deg",
        "inner_delta_final_deg",
        "outer_pwm_baseline",
        "outer_pwm_final",
        "phase7_pwm_common",
        "phase7_pwm_diff",
        "inner_mrac_reason",
        "inner_tv_reason",
        "rls_est_reason",
    ]

    with out_path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()

        for rank, (t, event_type, score, row_idx) in enumerate(events, start=1):
            row = rows[row_idx]
            out_row = {"event_rank": rank, "event_type": event_type, "event_score": score}
            for field in fields:
                if field in out_row:
                    continue
                out_row[field] = row.get(field, "")
            writer.writerow(out_row)

    return out_path


def plot_zoom(rows: List[dict], out_path: Path, title: str) -> None:
    t = [value(r, "_t") for r in rows]

    plt.figure(figsize=(11.0, 6.0))

    for key in KEYS_TO_PLOT:
        vals = []
        valid_t = []

        for row in rows:
            raw = to_float(row.get(key))
            if raw is None:
                continue
            valid_t.append(value(row, "_t"))
            vals.append(raw)

        if vals:
            plt.plot(valid_t, vals, linewidth=1.4, label=key)

    plt.title(title)
    plt.xlabel("time from first MRAC scaffold sample [s]")
    plt.ylabel("mixed diagnostic values")
    plt.grid(True)
    plt.legend(loc="best", fontsize=8)
    plt.tight_layout()
    plt.savefig(out_path, dpi=160)
    plt.close()


def plot_scatter(rows: List[dict], out_dir: Path) -> None:
    baseline = []
    final = []
    uc = []
    r = []

    for row in rows:
        b = to_float(row.get("inner_delta_baseline_deg"))
        f = to_float(row.get("inner_delta_final_deg"))
        u = to_float(row.get("inner_uc"))
        rr = to_float(row.get("r_recon"))

        if b is not None and f is not None:
            baseline.append(b)
            final.append(f)
        if u is not None and rr is not None:
            uc.append(u)
            r.append(rr)

    if baseline and final:
        plt.figure(figsize=(7.0, 7.0))
        plt.scatter(baseline, final, s=18)
        lim = max(max(abs(x) for x in baseline), max(abs(x) for x in final), 1.0)
        plt.plot([-lim, lim], [-lim, lim], linestyle="--")
        plt.title("Steering comparison: MRAC final vs baseline")
        plt.xlabel("baseline steering [deg]")
        plt.ylabel("MRAC final steering [deg]")
        plt.grid(True)
        plt.tight_layout()
        plt.savefig(out_dir / "scatter_inner_delta_final_vs_baseline.png", dpi=160)
        plt.close()

    if uc and r:
        plt.figure(figsize=(7.0, 7.0))
        plt.scatter(uc, r, s=18)
        lim = max(max(abs(x) for x in uc), max(abs(x) for x in r), 1.0e-6)
        plt.plot([-lim, lim], [-lim, lim], linestyle="--")
        plt.title("Yaw tracking: measured yaw rate vs command")
        plt.xlabel("inner_uc command [rad/s]")
        plt.ylabel("r_recon measured [rad/s]")
        plt.grid(True)
        plt.tight_layout()
        plt.savefig(out_dir / "scatter_r_recon_vs_inner_uc.png", dpi=160)
        plt.close()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("parsed_csv", nargs="?", help="Path to parsed_samples.csv")
    parser.add_argument("--top-n", type=int, default=8)
    parser.add_argument("--window-s", type=float, default=6.0)
    args = parser.parse_args()

    csv_path = Path(args.parsed_csv) if args.parsed_csv else latest_parsed_csv()
    if not csv_path.exists():
        raise SystemExit(f"File not found: {csv_path}")

    rows = read_csv(csv_path)

    out_dir = csv_path.parent / "turn_diagnostics"
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"input: {csv_path}")
    print(f"rows: {len(rows)}")
    print(f"output: {out_dir}")

    summary_path = write_summary(rows, out_dir)
    events = find_top_events(rows, args.top_n)
    events_path = write_events(rows, events, out_dir)

    print(f"[csv] {summary_path}")
    print(f"[csv] {events_path}")

    for rank, (t, event_type, score, row_idx) in enumerate(events, start=1):
        subset = window_rows(rows, t, args.window_s)
        out_path = out_dir / f"zoom_{rank:02d}_{event_type}_t_{t:.2f}s.png"
        title = f"{event_type}, t={t:.2f}s, score={score:.4g}"
        plot_zoom(subset, out_path, title)
        print(f"[plot] {out_path}")

    plot_scatter(rows, out_dir)
    print(f"[plot] {out_dir / 'scatter_inner_delta_final_vs_baseline.png'}")
    print(f"[plot] {out_dir / 'scatter_r_recon_vs_inner_uc.png'}")

    print()
    print("Most important next files:")
    print(f"  {events_path}")
    print(f"  {out_dir / 'scatter_inner_delta_final_vs_baseline.png'}")
    print(f"  {out_dir / 'scatter_r_recon_vs_inner_uc.png'}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
